Move footer to end of (large) screens
fsr-de/myHPI pull request #341
Opened 2023-04-17 20:42 UTC by FranzSw

Uses flexbox to move the footer to the end of the screen in cases where the content takes up less space than the screen is high.

I didn't talk to any contributor beforehand, so I'm not sure if you have any other plans, so feel free to just dismiss this PR if it doesnt fit :)

| Before | After |
| -- |-- |
|<img width="300" style="float: left" alt="image" src="https://user-images.githubusercontent.com/15076254/232605700-277af738-9daa-41f7-aace-b99340500820.png">|<img width="300" alt="image" style="float: right" src="https://user-images.githubusercontent.com/15076254/232605630-3becdc58-cf08-4790-9cc1-070dbab01dc8.png">|

_This pull request is brought to you by EvaP Hacking-Hours_

2023-04-19 19:14 UTC, SilvanVerhoeven requested changes
Apart from the code style, looks good :)

2023-04-19 19:14 UTC, SilvanVerhoeven commented on myhpi/static/scss/myHPI.scss
> +}
Please use the Bootstrap helper classes :)
https://getbootstrap.com/docs/5.0/utilities/flex/

2023-04-19 19:14 UTC, SilvanVerhoeven commented on myhpi/static/scss/myHPI.scss
> +}
Either use the bootstrap helper class or put it into `.page` (or remove `.page` and merge it into `#page`)

2024-06-11 19:21 UTC, jeriox commented
@FranzSw if you have a chance to address the review comments we would be happy to merge this :)

2024-07-30 10:55 UTC, closed without merging