Use tomselect
fsr-de/myHPI pull request #421
Opened 2023-11-09 20:27 UTC by frcroth

Fixes #411 and #336

2023-11-11 19:24 UTC, jeriox approved these changes
lgtm!
Could you use the display name of the user instead of the username? otherwise we need to change that again with the upcoming keycloak migration as the username will be the UUID from the OIDC sub claim in the future

2023-11-22 21:54 UTC, jeriox commented on myhpi/core/models.py
> +class UserProfile(models.Model):
I personally don't really like the proxy models and generally prefer substituting the user model as a whole. However, this seems to be a bit tricky for existing projects (https://docs.djangoproject.com/en/4.2/topics/auth/customizing/#changing-to-a-custom-user-model-mid-project).

2024-02-15 11:41 UTC, jeriox requested changes
currently blocked as we cannot use first+last name as label

2024-02-15 11:58 UTC, frcroth commented
Also created an issue for that: https://github.com/OmenApps/django-tomselect/issues/7

2024-07-31 18:31 UTC, jeriox commented
we looked at the code of django-tomselect and it turns out that they pass the label field name to their own js code, where it is templated to access the data in some js object. so calling a function/property on the python model is definetly not possible and using a composite label also seems quite hard. I'd vote to abandon the tomselect plan

2024-08-01 12:32 UTC, closed without merging

2024-12-18 08:49 UTC, frcroth commented
There has been a response: https://github.com/OmenApps/django-tomselect/issues/7#issuecomment-2546279475